server:
  port: 9990

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  scan:
    base-packages: com.example.dubboprovider.service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20000